DATA:
  root_dir: "data"

IMG:
  img_size: 224
  patch_size: 16

MODEL:
  IMG_PATCHER:
    latent_dim: 512
  ViT_ENCODER:
    n_heads: 4
  ViT:
    n_encoders: 12
  HEAD:
    n_classes: 37

TRAINING:
  batch_size: 4